apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: abc-deployment
spec:
  selector:
    matchLabels:
      app: abc
  replicas: 1 # tells deployment to run x pods matching the template
  template:
    metadata:
      labels:
        app: abc
    spec:
      containers:
        - name: abc
          image: abc:latest
          ports:
            - containerPort: 8088