apiVersion: apps/v1
kind: Deployment
metadata:
  name: abc-deployment
spec:
  selector:
    matchLabels:
      app: abc
  replicas: 1
  template:
    metadata:
      labels:
        app: abc
    spec:
      containers:
        - name: abc
          image: abc:latest
          ports:
            - containerPort: 8088