apiVersion: apps/v1
kind: Deployment
metadata:
  name: myimage-deployment
spec:
  selector:
    matchLabels:
      app: myimage
  replicas: 5
  template:
    metadata:
      labels:
        app: myimage
    spec:
      containers:
        - name: myimage
          image: myimage:latest
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 8088